compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  episerver:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com/episerver"
  optimizely:
    npmAlwaysAuth: true
    npmAuthIdent: "${ARTIFACTORY_USER}:${ARTIFACTORY_KEY}"
    npmRegistryServer: "https://optimizely.jfrog.io/optimizely/api/npm/npm/"

